### ISSUE TITLE
Autopilot crashes with a System.ArgumentException

### ISSUE THREAD

**Issue by zrisher** [Rynchodon/Autopilot#33]
@Rynchodon, I got this error this morning after about 10 hours running autopilot with 1-4 people:

```
2015-04-27 11:50:06.394 - Thread:   6 ->  Exception occured: System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Rynchodon.AntennaRelay.RemoteControl..ctor(IMyCubeBlock block)
   at Rynchodon.Update.UpdateManager.<RegisterScripts>b__5(IMyCubeBlock block)
   at Rynchodon.Update.UpdateManager.Grid_OnBlockAdded(IMySlimBlock block)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlockInternal(=Q6WknzTZKSlxBUSpPd9birHnHM= block)
   at Sandbox.Game.Entities.MyCubeGrid.MoveBlocks(MyCubeGrid from, MyCubeGrid to, List`1 cubeBlocks, Int32 offset, Int32 count)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplitForGroup(MyCubeGrid originalGrid, List`1 splitBlocks, =CltAozIeGZUP6CBv1M6w1Cr40Rd=& group)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplits(MyCubeGrid originalGrid, List`1 splitBlocks, List`1 groups, Boolean sync)
   at =48YcmBIQHJDORnZoKHwb5Pw9MM=.Disconnect(MyCubeGrid )
   at Sandbox.Game.Entities.MyCubeGrid.DetectDisconnects()
   at Sandbox.Game.Entities.MyCubeGrid.DoLazyUpdates()
   at Sandbox.Game.Entities.MyCubeGrid.UpdateBeforeSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at =zrstbH1ZeDq5UBSIpg1qnDziYP=.UpdateBeforeSimulation()
   at =GND6z8idGdIAcWcb2YBaSnRMp7=.UpdateComponents()
   at =GND6z8idGdIAcWcb2YBaSnRMp7=.Update(MyTimeSpan )
   at =JbLZcQ0hj347engCZ44EtlRZjA=.Update()
   at =f3Z6Ndh0u8AiCd1RYvZsU5Dv7T=.UpdateInternal()
   at =cuDXH07IPdNc3nh2dfXC4sNbx5=.=v0NoMtrPy2fhNeFawOHPKRCSMn=.<Run>b__1()
   at =mEhFnRRYUxEvoh0t4KZxxONkWU=.Run(=ikvYbcjVoXAAj7Kp0pbE1O7j9B= )
   at =cuDXH07IPdNc3nh2dfXC4sNbx5=.Run(=ikvYbcjVoXAAj7Kp0pbE1O7j9B= )
   at =JbLZcQ0hj347engCZ44EtlRZjA=.Run(Boolean , Action )
   at Sandbox.AppCode.App.MyProgram.RunInternal()
   at Sandbox.AppCode.App.MyProgram.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at Sandbox.AppCode.App.WindowsService.MainThreadStart(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

There's nothing in the Autopilot log for this date.

**Comment by Rynchodon** [comment]
Stupid merge blocks... Fix is in master.

**Comment by zrisher** [comment]
Yay thank you!
